<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
    <title>@yield('title', 'Operations') · LedgerFlow</title>
    <style>
        :root{--ink:#172033;--muted:#667085;--line:#e5e7eb;--paper:#fff;--bg:#f4f7fb;--brand:#165dff;--good:#067647;--bad:#b42318;--warn:#b54708}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.5 Inter,ui-sans-serif,system-ui,sans-serif}a{color:inherit;text-decoration:none}.shell{display:grid;grid-template-columns:240px 1fr;min-height:100vh}.side{background:#101828;color:#d0d5dd;padding:24px 16px}.logo{color:#fff;font-size:20px;font-weight:800;padding:0 10px 24px}.nav a{display:block;padding:10px 12px;border-radius:8px;margin:4px 0}.nav a:hover{background:#1d2939;color:#fff}.main{padding:28px 34px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}h1{font-size:26px;margin:0}h2{font-size:17px;margin:0 0 14px}.muted{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.card{background:var(--paper);border:1px solid var(--line);border-radius:12px;padding:18px;box-shadow:0 1px 2px #1018280d}.metric{font-size:28px;font-weight:750;margin-top:6px}.table-card{background:#fff;border:1px solid var(--line);border-radius:12px;overflow:hidden;margin-top:20px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:12px 14px;border-bottom:1px solid var(--line);vertical-align:top}th{font-size:12px;text-transform:uppercase;letter-spacing:.04em;color:var(--muted);background:#f9fafb}.badge{display:inline-block;padding:3px 8px;border-radius:99px;background:#eef2f6;font-size:12px}.badge.completed,.badge.balanced{background:#ecfdf3;color:var(--good)}.badge.failed,.badge.discrepancy{background:#fef3f2;color:var(--bad)}.badge.processing,.badge.pending{background:#fffaeb;color:var(--warn)}.filters{display:flex;gap:10px;flex-wrap:wrap}.input,select{height:40px;border:1px solid #d0d5dd;border-radius:8px;background:#fff;padding:0 11px}.button{height:40px;border:0;border-radius:8px;padding:0 15px;background:var(--brand);color:#fff;font-weight:650;cursor:pointer}.button.secondary{background:#344054}.split{display:grid;grid-template-columns:2fr 1fr;gap:20px}.kv{display:grid;grid-template-columns:180px 1fr;gap:8px 18px}.amount{font-variant-numeric:tabular-nums;font-weight:650}.alert{padding:12px 14px;border-radius:8px;background:#ecfdf3;color:var(--good);margin-bottom:16px}.error{background:#fef3f2;color:var(--bad)}@media(max-width:900px){.shell{grid-template-columns:1fr}.side{display:none}.main{padding:18px}.grid{grid-template-columns:repeat(2,1fr)}.split{grid-template-columns:1fr}}
    </style>
</head>
<body><div class="shell"><aside class="side"><div class="logo">LedgerFlow</div><nav class="nav"><a href="{{ route('admin.dashboard') }}">Overview</a><a href="{{ route('admin.transactions.index') }}">Transactions</a><a href="{{ route('admin.reconciliation.index') }}">Reconciliation</a></nav></aside><main class="main"><div class="top"><div><h1>@yield('heading')</h1><div class="muted">Financial operations console</div></div><form method="post" action="{{ route('admin.logout') }}">@csrf<button class="button secondary">Sign out</button></form></div>@if(session('status'))<div class="alert">{{ session('status') }}</div>@endif @yield('content')</main></div></body></html>
